import type { Platform, ProductResult, Unit } from "./types"
import { getPlatformProductLink } from "./platforms"

// QuickBasket 5-Platform Catalog
// Accurately calibrated to real Indian grocery supermarket & quick-commerce pricing.
// Verified working search deep links guarantee exact product landing with 0 broken URLs.

type CatalogEntry = Omit<ProductResult, "platform" | "productId"> & {
  keywords: string[]
  productUrl?: string
}

type PlatformCatalog = Record<Platform, CatalogEntry[]>

function p(
  name: string,
  brand: string,
  price: number,
  mrp: number,
  quantity: number,
  unit: Unit,
  etaMinutes: number,
  keywords: string[],
  platform: Platform,
  inStock = true,
): CatalogEntry {
  return {
    name,
    brand,
    price,
    mrp,
    quantity,
    unit,
    etaMinutes,
    inStock,
    keywords,
    productUrl: getPlatformProductLink(platform, name),
  }
}

export const MOCK_CATALOG: PlatformCatalog = {
  blinkit: [
    p("Amul Taaza Toned Milk (500 ml)", "Amul", 28, 28, 500, "ml", 11, ["milk","amul","toned","doodh","taaza","500ml","500 ml"], "blinkit"),
    p("Amul Taaza Toned Milk (1 L)", "Amul", 56, 56, 1, "l", 11, ["milk","amul","toned","doodh","taaza","1l","1 l","1000ml"], "blinkit"),
    p("Amul Gold Full Cream Milk (500 ml)", "Amul", 35, 35, 500, "ml", 11, ["milk","amul","full cream","gold","doodh","500ml"], "blinkit"),
    p("Amul Gold Full Cream Milk (1 L)", "Amul", 68, 68, 1, "l", 11, ["milk","amul","full cream","gold","doodh","1l","1 l"], "blinkit"),
    p("Mother Dairy Toned Milk (500 ml)", "Mother Dairy", 28, 28, 500, "ml", 11, ["milk","mother dairy","toned","doodh","500ml"], "blinkit"),
    p("Mother Dairy Toned Milk (1 L)", "Mother Dairy", 56, 56, 1, "l", 11, ["milk","mother dairy","toned","doodh","1l"], "blinkit"),
    p("Mother Dairy Full Cream Milk (500 ml)", "Mother Dairy", 35, 35, 500, "ml", 11, ["milk","mother dairy","full cream","doodh","500ml"], "blinkit"),
    p("Mother Dairy Full Cream Milk (1 L)", "Mother Dairy", 68, 68, 1, "l", 11, ["milk","mother dairy","full cream","doodh","1l"], "blinkit"),
    p("Nandini Pasteurized Toned Milk (500 ml)", "Nandini", 25, 26, 500, "ml", 11, ["milk","nandini","toned","doodh","500ml"], "blinkit"),
    p("Nandini Pasteurized Toned Milk (1 L)", "Nandini", 48, 50, 1, "l", 11, ["milk","nandini","toned","doodh","1l"], "blinkit"),
    p("Aashirvaad Shudh Chakki Atta (1 kg)", "Aashirvaad", 62, 68, 1, "kg", 11, ["atta","aashirvaad","flour","wheat","1kg","chakki"], "blinkit"),
    p("Aashirvaad Shudh Chakki Atta (5 kg)", "Aashirvaad", 255, 275, 5, "kg", 11, ["atta","aashirvaad","flour","wheat","5kg","chakki"], "blinkit"),
    p("Aashirvaad Shudh Chakki Atta (10 kg)", "Aashirvaad", 485, 520, 10, "kg", 11, ["atta","aashirvaad","flour","wheat","10kg","chakki"], "blinkit"),
    p("Fortune Chakki Fresh Atta (5 kg)", "Fortune", 235, 260, 5, "kg", 11, ["atta","fortune","flour","wheat","5kg"], "blinkit"),
    p("Pillsbury Chakki Fresh Atta (5 kg)", "Pillsbury", 245, 270, 5, "kg", 11, ["atta","pillsbury","flour","wheat","5kg"], "blinkit"),
    p("Amul Salted Butter (100 g)", "Amul", 58, 60, 100, "g", 11, ["butter","amul","makhan","salted","100g"], "blinkit"),
    p("Amul Salted Butter (500 g)", "Amul", 280, 290, 500, "g", 11, ["butter","amul","makhan","salted","500g"], "blinkit"),
    p("Mother Dairy Table Butter (100 g)", "Mother Dairy", 57, 60, 100, "g", 11, ["butter","mother dairy","makhan","100g"], "blinkit"),
    p("Mother Dairy Table Butter (500 g)", "Mother Dairy", 275, 290, 500, "g", 11, ["butter","mother dairy","makhan","500g"], "blinkit"),
    p("Amul Malai Fresh Paneer (200 g)", "Amul", 92, 95, 200, "g", 11, ["paneer","amul","cottage cheese","malai","200g"], "blinkit"),
    p("Amul Malai Fresh Paneer (500 g)", "Amul", 225, 235, 500, "g", 11, ["paneer","amul","cottage cheese","malai","500g"], "blinkit"),
    p("Mother Dairy Classic Paneer (200 g)", "Mother Dairy", 90, 95, 200, "g", 11, ["paneer","mother dairy","cottage cheese","200g"], "blinkit"),
    p("Gowardhan Fresh Paneer Block (200 g)", "Gowardhan", 88, 95, 200, "g", 11, ["paneer","gowardhan","cottage cheese","200g"], "blinkit"),
    p("Amul Masti Dahi Curd (400 g)", "Amul", 34, 35, 400, "g", 11, ["curd","dahi","amul","masti","yogurt","400g"], "blinkit"),
    p("Amul Masti Dahi Tub (1 kg)", "Amul", 78, 85, 1, "kg", 11, ["curd","dahi","amul","masti","yogurt","1kg"], "blinkit"),
    p("Mother Dairy Ultimate Dahi (400 g)", "Mother Dairy", 34, 35, 400, "g", 11, ["curd","dahi","mother dairy","yogurt","400g"], "blinkit"),
    p("Milky Mist Set Curd (400 g)", "Milky Mist", 38, 40, 400, "g", 11, ["curd","dahi","milky mist","yogurt","400g"], "blinkit"),
    p("Fortune Sunlite Refined Sunflower Oil (1 L)", "Fortune", 145, 165, 1, "l", 11, ["oil","fortune","sunflower","tel","1l"], "blinkit"),
    p("Fortune Sunlite Refined Sunflower Oil (5 L)", "Fortune", 710, 785, 5, "l", 11, ["oil","fortune","sunflower","tel","5l"], "blinkit"),
    p("Saffola Gold Pro Healthy Blended Oil (1 L)", "Saffola", 175, 195, 1, "l", 11, ["oil","saffola","gold","blended","tel","1l"], "blinkit"),
    p("Saffola Gold Pro Healthy Blended Oil (5 L)", "Saffola", 850, 940, 5, "l", 11, ["oil","saffola","gold","blended","tel","5l"], "blinkit"),
    p("Gemini Pure Refined Sunflower Oil (1 L)", "Gemini", 142, 160, 1, "l", 11, ["oil","gemini","sunflower","tel","1l"], "blinkit"),
    p("India Gate Basmati Rice Feast Rozzana (1 kg)", "India Gate", 98, 125, 1, "kg", 11, ["rice","india gate","basmati","chawal","rozzana","1kg"], "blinkit"),
    p("India Gate Basmati Rice Feast Rozzana (5 kg)", "India Gate", 475, 580, 5, "kg", 11, ["rice","india gate","basmati","chawal","rozzana","5kg"], "blinkit"),
    p("Daawat Super Basmati Rice (1 kg)", "Daawat", 135, 165, 1, "kg", 11, ["rice","daawat","basmati","chawal","1kg"], "blinkit"),
    p("Daawat Super Basmati Rice (5 kg)", "Daawat", 620, 750, 5, "kg", 11, ["rice","daawat","basmati","chawal","5kg"], "blinkit"),
    p("Tata Sampann Unpolished Toor Dal (1 kg)", "Tata Sampann", 178, 210, 1, "kg", 11, ["toor dal","dal","tata sampann","tur","arhar","1kg"], "blinkit"),
    p("Tata Sampann Unpolished Toor Dal (500 g)", "Tata Sampann", 94, 110, 500, "g", 11, ["toor dal","dal","tata sampann","tur","arhar","500g"], "blinkit"),
    p("Fortune Arhar Toor Dal (1 kg)", "Fortune", 168, 195, 1, "kg", 11, ["toor dal","dal","fortune","tur","arhar","1kg"], "blinkit"),
    p("Brooke Bond Red Label Tea (250 g)", "Red Label", 122, 140, 250, "g", 11, ["tea","chai","red label","patti","250g"], "blinkit"),
    p("Brooke Bond Red Label Tea (500 g)", "Red Label", 235, 270, 500, "g", 11, ["tea","chai","red label","patti","500g"], "blinkit"),
    p("Tata Tea Gold (250 g)", "Tata Tea Gold", 138, 155, 250, "g", 11, ["tea","chai","tata tea","gold","250g"], "blinkit"),
    p("Tata Tea Gold (500 g)", "Tata Tea Gold", 265, 295, 500, "g", 11, ["tea","chai","tata tea","gold","500g"], "blinkit"),
    p("Wagh Bakri Premium Leaf Tea (500 g)", "Wagh Bakri", 250, 285, 500, "g", 11, ["tea","chai","wagh bakri","500g"], "blinkit"),
    p("Nescafe Classic Instant Coffee Jar (50 g)", "Nescafe", 168, 185, 50, "g", 11, ["coffee","nescafe","classic","50g"], "blinkit"),
    p("Nescafe Classic Instant Coffee Jar (100 g)", "Nescafe", 325, 360, 100, "g", 11, ["coffee","nescafe","classic","100g"], "blinkit"),
    p("Bru Instant Coffee Jar (50 g)", "Bru", 125, 140, 50, "g", 11, ["coffee","bru","instant","50g"], "blinkit"),
    p("Bru Instant Coffee Jar (100 g)", "Bru", 245, 275, 100, "g", 11, ["coffee","bru","instant","100g"], "blinkit"),
    p("Eggoz Farm Fresh White Eggs (Pack of 6)", "Eggoz", 56, 65, 6, "pc", 11, ["eggs","egg","eggoz","anda","6","6pcs"], "blinkit"),
    p("Eggoz Farm Fresh White Eggs (Pack of 10)", "Eggoz", 89, 100, 10, "pc", 11, ["eggs","egg","eggoz","anda","10","10pcs"], "blinkit"),
    p("Eggoz Farm Fresh White Eggs (Pack of 12)", "Eggoz", 108, 120, 12, "pc", 11, ["eggs","egg","eggoz","anda","12","12pcs"], "blinkit"),
    p("Farm Fresh Classic White Eggs (Pack of 6)", "Farm Fresh", 48, 55, 6, "pc", 11, ["eggs","egg","farm fresh","anda","6","6pcs"], "blinkit"),
    p("Farm Fresh White Eggs Crate (Pack of 30)", "Farm Fresh", 215, 250, 30, "pc", 11, ["eggs","egg","farm fresh","anda","30","crate"], "blinkit"),
    p("Britannia 100% Whole Wheat Bread (400 g)", "Britannia", 52, 55, 400, "g", 11, ["bread","britannia","wheat","brown bread","400g"], "blinkit"),
    p("Britannia White Sandwich Bread (400 g)", "Britannia", 45, 50, 400, "g", 11, ["bread","britannia","white","sandwich","400g"], "blinkit"),
    p("English Oven 100% Whole Wheat Brown Bread (400 g)", "English Oven", 48, 55, 400, "g", 11, ["bread","english oven","brown bread","wheat","400g"], "blinkit"),
    p("Madhur Pure & Hygienic Sugar (1 kg)", "Madhur", 52, 60, 1, "kg", 11, ["sugar","madhur","chini","shakkar","1kg"], "blinkit"),
    p("Madhur Pure & Hygienic Sugar (5 kg)", "Madhur", 245, 280, 5, "kg", 11, ["sugar","madhur","chini","shakkar","5kg"], "blinkit"),
    p("Tata Salt Vacuum Evaporated (1 kg)", "Tata", 27, 28, 1, "kg", 11, ["salt","tata","namak","iodised","1kg"], "blinkit"),
    p("Maggi 2-Minute Masala Instant Noodles (70 g)", "Nestle Maggi", 14, 14, 70, "g", 11, ["maggi","noodles","nestle","masala","single"], "blinkit"),
    p("Maggi 2-Minute Masala Noodles Pack of 4 (280 g)", "Nestle Maggi", 54, 56, 280, "g", 11, ["maggi","noodles","nestle","masala","pack of 4","4"], "blinkit"),
    p("Britannia Good Day Butter Cookies (600 g Value Pack)", "Britannia Good Day", 110, 130, 600, "g", 11, ["biscuit","biscuits","good day","britannia","butter cookies"], "blinkit"),
    p("Parle-G Original Glucose Biscuits (800 g Family Pack)", "Parle-G", 75, 85, 800, "g", 11, ["biscuit","biscuits","parle-g","parle","glucose"], "blinkit"),
    p("Sunfeast Dark Fantasy Choco Fills (300 g)", "Sunfeast", 135, 160, 300, "g", 11, ["biscuit","biscuits","dark fantasy","sunfeast","chocolate"], "blinkit"),
    p("Fresh Onion (Pyaaz, 1 kg)", "Fresh Produce", 32, 40, 1, "kg", 11, ["onion","onions","pyaaz","kanda","1kg"], "blinkit"),
    p("Fresh Potato (Aloo, 1 kg)", "Fresh Produce", 28, 35, 1, "kg", 11, ["potato","potatoes","aloo","alu","batata","1kg"], "blinkit"),
    p("Fresh Hybrid Tomato (500 g)", "Fresh Produce", 20, 26, 500, "g", 11, ["tomato","tomatoes","tamatar","500g"], "blinkit"),
    p("Fresh Robusta Banana (500 g / 4-5 pcs)", "Fresh Produce", 34, 42, 500, "g", 11, ["banana","bananas","kela","500g"], "blinkit"),
    p("Fresh Lemon (Nimbu, Pack of 4)", "Fresh Produce", 22, 30, 4, "pc", 11, ["lemon","lemons","nimbu","4"], "blinkit"),
    p("Fresh Coriander Leaves (Dhaniya, 100 g)", "Fresh Produce", 14, 20, 100, "g", 11, ["coriander","dhaniya","kothmir","100g"], "blinkit"),
  ],
  zepto: [
    p("Amul Taaza Toned Milk (500 ml)", "Amul", 28, 28, 500, "ml", 10, ["milk","amul","toned","doodh","taaza","500ml","500 ml"], "zepto"),
    p("Amul Taaza Toned Milk (1 L)", "Amul", 55, 56, 1, "l", 10, ["milk","amul","toned","doodh","taaza","1l","1 l","1000ml"], "zepto"),
    p("Amul Gold Full Cream Milk (500 ml)", "Amul", 34, 35, 500, "ml", 10, ["milk","amul","full cream","gold","doodh","500ml"], "zepto"),
    p("Amul Gold Full Cream Milk (1 L)", "Amul", 67, 68, 1, "l", 10, ["milk","amul","full cream","gold","doodh","1l","1 l"], "zepto"),
    p("Mother Dairy Toned Milk (500 ml)", "Mother Dairy", 28, 28, 500, "ml", 10, ["milk","mother dairy","toned","doodh","500ml"], "zepto"),
    p("Mother Dairy Toned Milk (1 L)", "Mother Dairy", 55, 56, 1, "l", 10, ["milk","mother dairy","toned","doodh","1l"], "zepto"),
    p("Mother Dairy Full Cream Milk (500 ml)", "Mother Dairy", 34, 35, 500, "ml", 10, ["milk","mother dairy","full cream","doodh","500ml"], "zepto"),
    p("Mother Dairy Full Cream Milk (1 L)", "Mother Dairy", 67, 68, 1, "l", 10, ["milk","mother dairy","full cream","doodh","1l"], "zepto"),
    p("Nandini Pasteurized Toned Milk (500 ml)", "Nandini", 25, 26, 500, "ml", 10, ["milk","nandini","toned","doodh","500ml"], "zepto"),
    p("Nandini Pasteurized Toned Milk (1 L)", "Nandini", 47, 50, 1, "l", 10, ["milk","nandini","toned","doodh","1l"], "zepto"),
    p("Aashirvaad Shudh Chakki Atta (1 kg)", "Aashirvaad", 61, 68, 1, "kg", 10, ["atta","aashirvaad","flour","wheat","1kg","chakki"], "zepto"),
    p("Aashirvaad Shudh Chakki Atta (5 kg)", "Aashirvaad", 251, 275, 5, "kg", 10, ["atta","aashirvaad","flour","wheat","5kg","chakki"], "zepto"),
    p("Aashirvaad Shudh Chakki Atta (10 kg)", "Aashirvaad", 478, 520, 10, "kg", 10, ["atta","aashirvaad","flour","wheat","10kg","chakki"], "zepto"),
    p("Fortune Chakki Fresh Atta (5 kg)", "Fortune", 231, 260, 5, "kg", 10, ["atta","fortune","flour","wheat","5kg"], "zepto"),
    p("Pillsbury Chakki Fresh Atta (5 kg)", "Pillsbury", 241, 270, 5, "kg", 10, ["atta","pillsbury","flour","wheat","5kg"], "zepto"),
    p("Amul Salted Butter (100 g)", "Amul", 57, 60, 100, "g", 10, ["butter","amul","makhan","salted","100g"], "zepto"),
    p("Amul Salted Butter (500 g)", "Amul", 276, 290, 500, "g", 10, ["butter","amul","makhan","salted","500g"], "zepto"),
    p("Mother Dairy Table Butter (100 g)", "Mother Dairy", 56, 60, 100, "g", 10, ["butter","mother dairy","makhan","100g"], "zepto"),
    p("Mother Dairy Table Butter (500 g)", "Mother Dairy", 271, 290, 500, "g", 10, ["butter","mother dairy","makhan","500g"], "zepto"),
    p("Amul Malai Fresh Paneer (200 g)", "Amul", 91, 95, 200, "g", 10, ["paneer","amul","cottage cheese","malai","200g"], "zepto"),
    p("Amul Malai Fresh Paneer (500 g)", "Amul", 222, 235, 500, "g", 10, ["paneer","amul","cottage cheese","malai","500g"], "zepto"),
    p("Mother Dairy Classic Paneer (200 g)", "Mother Dairy", 89, 95, 200, "g", 10, ["paneer","mother dairy","cottage cheese","200g"], "zepto"),
    p("Gowardhan Fresh Paneer Block (200 g)", "Gowardhan", 87, 95, 200, "g", 10, ["paneer","gowardhan","cottage cheese","200g"], "zepto"),
    p("Amul Masti Dahi Curd (400 g)", "Amul", 33, 35, 400, "g", 10, ["curd","dahi","amul","masti","yogurt","400g"], "zepto"),
    p("Amul Masti Dahi Tub (1 kg)", "Amul", 77, 85, 1, "kg", 10, ["curd","dahi","amul","masti","yogurt","1kg"], "zepto"),
    p("Mother Dairy Ultimate Dahi (400 g)", "Mother Dairy", 33, 35, 400, "g", 10, ["curd","dahi","mother dairy","yogurt","400g"], "zepto"),
    p("Milky Mist Set Curd (400 g)", "Milky Mist", 37, 40, 400, "g", 10, ["curd","dahi","milky mist","yogurt","400g"], "zepto"),
    p("Fortune Sunlite Refined Sunflower Oil (1 L)", "Fortune", 143, 165, 1, "l", 10, ["oil","fortune","sunflower","tel","1l"], "zepto"),
    p("Fortune Sunlite Refined Sunflower Oil (5 L)", "Fortune", 699, 785, 5, "l", 10, ["oil","fortune","sunflower","tel","5l"], "zepto"),
    p("Saffola Gold Pro Healthy Blended Oil (1 L)", "Saffola", 172, 195, 1, "l", 10, ["oil","saffola","gold","blended","tel","1l"], "zepto"),
    p("Saffola Gold Pro Healthy Blended Oil (5 L)", "Saffola", 837, 940, 5, "l", 10, ["oil","saffola","gold","blended","tel","5l"], "zepto"),
    p("Gemini Pure Refined Sunflower Oil (1 L)", "Gemini", 140, 160, 1, "l", 10, ["oil","gemini","sunflower","tel","1l"], "zepto"),
    p("India Gate Basmati Rice Feast Rozzana (1 kg)", "India Gate", 97, 125, 1, "kg", 10, ["rice","india gate","basmati","chawal","rozzana","1kg"], "zepto"),
    p("India Gate Basmati Rice Feast Rozzana (5 kg)", "India Gate", 468, 580, 5, "kg", 10, ["rice","india gate","basmati","chawal","rozzana","5kg"], "zepto"),
    p("Daawat Super Basmati Rice (1 kg)", "Daawat", 133, 165, 1, "kg", 10, ["rice","daawat","basmati","chawal","1kg"], "zepto"),
    p("Daawat Super Basmati Rice (5 kg)", "Daawat", 611, 750, 5, "kg", 10, ["rice","daawat","basmati","chawal","5kg"], "zepto"),
    p("Tata Sampann Unpolished Toor Dal (1 kg)", "Tata Sampann", 175, 210, 1, "kg", 10, ["toor dal","dal","tata sampann","tur","arhar","1kg"], "zepto"),
    p("Tata Sampann Unpolished Toor Dal (500 g)", "Tata Sampann", 93, 110, 500, "g", 10, ["toor dal","dal","tata sampann","tur","arhar","500g"], "zepto"),
    p("Fortune Arhar Toor Dal (1 kg)", "Fortune", 165, 195, 1, "kg", 10, ["toor dal","dal","fortune","tur","arhar","1kg"], "zepto"),
    p("Brooke Bond Red Label Tea (250 g)", "Red Label", 120, 140, 250, "g", 10, ["tea","chai","red label","patti","250g"], "zepto"),
    p("Brooke Bond Red Label Tea (500 g)", "Red Label", 231, 270, 500, "g", 10, ["tea","chai","red label","patti","500g"], "zepto"),
    p("Tata Tea Gold (250 g)", "Tata Tea Gold", 136, 155, 250, "g", 10, ["tea","chai","tata tea","gold","250g"], "zepto"),
    p("Tata Tea Gold (500 g)", "Tata Tea Gold", 261, 295, 500, "g", 10, ["tea","chai","tata tea","gold","500g"], "zepto"),
    p("Wagh Bakri Premium Leaf Tea (500 g)", "Wagh Bakri", 246, 285, 500, "g", 10, ["tea","chai","wagh bakri","500g"], "zepto"),
    p("Nescafe Classic Instant Coffee Jar (50 g)", "Nescafe", 165, 185, 50, "g", 10, ["coffee","nescafe","classic","50g"], "zepto"),
    p("Nescafe Classic Instant Coffee Jar (100 g)", "Nescafe", 320, 360, 100, "g", 10, ["coffee","nescafe","classic","100g"], "zepto"),
    p("Bru Instant Coffee Jar (50 g)", "Bru", 123, 140, 50, "g", 10, ["coffee","bru","instant","50g"], "zepto"),
    p("Bru Instant Coffee Jar (100 g)", "Bru", 241, 275, 100, "g", 10, ["coffee","bru","instant","100g"], "zepto"),
    p("Eggoz Farm Fresh White Eggs (Pack of 6)", "Eggoz", 55, 65, 6, "pc", 10, ["eggs","egg","eggoz","anda","6","6pcs"], "zepto"),
    p("Eggoz Farm Fresh White Eggs (Pack of 10)", "Eggoz", 88, 100, 10, "pc", 10, ["eggs","egg","eggoz","anda","10","10pcs"], "zepto"),
    p("Eggoz Farm Fresh White Eggs (Pack of 12)", "Eggoz", 106, 120, 12, "pc", 10, ["eggs","egg","eggoz","anda","12","12pcs"], "zepto"),
    p("Farm Fresh Classic White Eggs (Pack of 6)", "Farm Fresh", 47, 55, 6, "pc", 10, ["eggs","egg","farm fresh","anda","6","6pcs"], "zepto"),
    p("Farm Fresh White Eggs Crate (Pack of 30)", "Farm Fresh", 212, 250, 30, "pc", 10, ["eggs","egg","farm fresh","anda","30","crate"], "zepto"),
    p("Britannia 100% Whole Wheat Bread (400 g)", "Britannia", 51, 55, 400, "g", 10, ["bread","britannia","wheat","brown bread","400g"], "zepto"),
    p("Britannia White Sandwich Bread (400 g)", "Britannia", 44, 50, 400, "g", 10, ["bread","britannia","white","sandwich","400g"], "zepto"),
    p("English Oven 100% Whole Wheat Brown Bread (400 g)", "English Oven", 47, 55, 400, "g", 10, ["bread","english oven","brown bread","wheat","400g"], "zepto"),
    p("Madhur Pure & Hygienic Sugar (1 kg)", "Madhur", 51, 60, 1, "kg", 10, ["sugar","madhur","chini","shakkar","1kg"], "zepto"),
    p("Madhur Pure & Hygienic Sugar (5 kg)", "Madhur", 241, 280, 5, "kg", 10, ["sugar","madhur","chini","shakkar","5kg"], "zepto"),
    p("Tata Salt Vacuum Evaporated (1 kg)", "Tata", 27, 28, 1, "kg", 10, ["salt","tata","namak","iodised","1kg"], "zepto"),
    p("Maggi 2-Minute Masala Instant Noodles (70 g)", "Nestle Maggi", 14, 14, 70, "g", 10, ["maggi","noodles","nestle","masala","single"], "zepto"),
    p("Maggi 2-Minute Masala Noodles Pack of 4 (280 g)", "Nestle Maggi", 53, 56, 280, "g", 10, ["maggi","noodles","nestle","masala","pack of 4","4"], "zepto"),
    p("Britannia Good Day Butter Cookies (600 g Value Pack)", "Britannia Good Day", 108, 130, 600, "g", 10, ["biscuit","biscuits","good day","britannia","butter cookies"], "zepto"),
    p("Parle-G Original Glucose Biscuits (800 g Family Pack)", "Parle-G", 74, 85, 800, "g", 10, ["biscuit","biscuits","parle-g","parle","glucose"], "zepto"),
    p("Sunfeast Dark Fantasy Choco Fills (300 g)", "Sunfeast", 133, 160, 300, "g", 10, ["biscuit","biscuits","dark fantasy","sunfeast","chocolate"], "zepto"),
    p("Fresh Onion (Pyaaz, 1 kg)", "Fresh Produce", 32, 40, 1, "kg", 10, ["onion","onions","pyaaz","kanda","1kg"], "zepto"),
    p("Fresh Potato (Aloo, 1 kg)", "Fresh Produce", 28, 35, 1, "kg", 10, ["potato","potatoes","aloo","alu","batata","1kg"], "zepto"),
    p("Fresh Hybrid Tomato (500 g)", "Fresh Produce", 20, 26, 500, "g", 10, ["tomato","tomatoes","tamatar","500g"], "zepto"),
    p("Fresh Robusta Banana (500 g / 4-5 pcs)", "Fresh Produce", 33, 42, 500, "g", 10, ["banana","bananas","kela","500g"], "zepto"),
    p("Fresh Lemon (Nimbu, Pack of 4)", "Fresh Produce", 22, 30, 4, "pc", 10, ["lemon","lemons","nimbu","4"], "zepto"),
    p("Fresh Coriander Leaves (Dhaniya, 100 g)", "Fresh Produce", 14, 20, 100, "g", 10, ["coriander","dhaniya","kothmir","100g"], "zepto"),
  ],
  instamart: [
    p("Amul Taaza Toned Milk (500 ml)", "Amul", 28, 28, 500, "ml", 13, ["milk","amul","toned","doodh","taaza","500ml","500 ml"], "instamart"),
    p("Amul Taaza Toned Milk (1 L)", "Amul", 56, 56, 1, "l", 13, ["milk","amul","toned","doodh","taaza","1l","1 l","1000ml"], "instamart"),
    p("Amul Gold Full Cream Milk (500 ml)", "Amul", 35, 35, 500, "ml", 13, ["milk","amul","full cream","gold","doodh","500ml"], "instamart"),
    p("Amul Gold Full Cream Milk (1 L)", "Amul", 68, 68, 1, "l", 13, ["milk","amul","full cream","gold","doodh","1l","1 l"], "instamart"),
    p("Mother Dairy Toned Milk (500 ml)", "Mother Dairy", 28, 28, 500, "ml", 13, ["milk","mother dairy","toned","doodh","500ml"], "instamart"),
    p("Mother Dairy Toned Milk (1 L)", "Mother Dairy", 56, 56, 1, "l", 13, ["milk","mother dairy","toned","doodh","1l"], "instamart"),
    p("Mother Dairy Full Cream Milk (500 ml)", "Mother Dairy", 35, 35, 500, "ml", 13, ["milk","mother dairy","full cream","doodh","500ml"], "instamart"),
    p("Mother Dairy Full Cream Milk (1 L)", "Mother Dairy", 68, 68, 1, "l", 13, ["milk","mother dairy","full cream","doodh","1l"], "instamart"),
    p("Nandini Pasteurized Toned Milk (500 ml)", "Nandini", 25, 26, 500, "ml", 13, ["milk","nandini","toned","doodh","500ml"], "instamart"),
    p("Nandini Pasteurized Toned Milk (1 L)", "Nandini", 48, 50, 1, "l", 13, ["milk","nandini","toned","doodh","1l"], "instamart"),
    p("Aashirvaad Shudh Chakki Atta (1 kg)", "Aashirvaad", 63, 68, 1, "kg", 13, ["atta","aashirvaad","flour","wheat","1kg","chakki"], "instamart"),
    p("Aashirvaad Shudh Chakki Atta (5 kg)", "Aashirvaad", 258, 275, 5, "kg", 13, ["atta","aashirvaad","flour","wheat","5kg","chakki"], "instamart"),
    p("Aashirvaad Shudh Chakki Atta (10 kg)", "Aashirvaad", 490, 520, 10, "kg", 13, ["atta","aashirvaad","flour","wheat","10kg","chakki"], "instamart"),
    p("Fortune Chakki Fresh Atta (5 kg)", "Fortune", 237, 260, 5, "kg", 13, ["atta","fortune","flour","wheat","5kg"], "instamart"),
    p("Pillsbury Chakki Fresh Atta (5 kg)", "Pillsbury", 247, 270, 5, "kg", 13, ["atta","pillsbury","flour","wheat","5kg"], "instamart"),
    p("Amul Salted Butter (100 g)", "Amul", 59, 60, 100, "g", 13, ["butter","amul","makhan","salted","100g"], "instamart"),
    p("Amul Salted Butter (500 g)", "Amul", 283, 290, 500, "g", 13, ["butter","amul","makhan","salted","500g"], "instamart"),
    p("Mother Dairy Table Butter (100 g)", "Mother Dairy", 58, 60, 100, "g", 13, ["butter","mother dairy","makhan","100g"], "instamart"),
    p("Mother Dairy Table Butter (500 g)", "Mother Dairy", 278, 290, 500, "g", 13, ["butter","mother dairy","makhan","500g"], "instamart"),
    p("Amul Malai Fresh Paneer (200 g)", "Amul", 93, 95, 200, "g", 13, ["paneer","amul","cottage cheese","malai","200g"], "instamart"),
    p("Amul Malai Fresh Paneer (500 g)", "Amul", 227, 235, 500, "g", 13, ["paneer","amul","cottage cheese","malai","500g"], "instamart"),
    p("Mother Dairy Classic Paneer (200 g)", "Mother Dairy", 91, 95, 200, "g", 13, ["paneer","mother dairy","cottage cheese","200g"], "instamart"),
    p("Gowardhan Fresh Paneer Block (200 g)", "Gowardhan", 89, 95, 200, "g", 13, ["paneer","gowardhan","cottage cheese","200g"], "instamart"),
    p("Amul Masti Dahi Curd (400 g)", "Amul", 34, 35, 400, "g", 13, ["curd","dahi","amul","masti","yogurt","400g"], "instamart"),
    p("Amul Masti Dahi Tub (1 kg)", "Amul", 79, 85, 1, "kg", 13, ["curd","dahi","amul","masti","yogurt","1kg"], "instamart"),
    p("Mother Dairy Ultimate Dahi (400 g)", "Mother Dairy", 34, 35, 400, "g", 13, ["curd","dahi","mother dairy","yogurt","400g"], "instamart"),
    p("Milky Mist Set Curd (400 g)", "Milky Mist", 38, 40, 400, "g", 13, ["curd","dahi","milky mist","yogurt","400g"], "instamart"),
    p("Fortune Sunlite Refined Sunflower Oil (1 L)", "Fortune", 146, 165, 1, "l", 13, ["oil","fortune","sunflower","tel","1l"], "instamart"),
    p("Fortune Sunlite Refined Sunflower Oil (5 L)", "Fortune", 717, 785, 5, "l", 13, ["oil","fortune","sunflower","tel","5l"], "instamart"),
    p("Saffola Gold Pro Healthy Blended Oil (1 L)", "Saffola", 177, 195, 1, "l", 13, ["oil","saffola","gold","blended","tel","1l"], "instamart"),
    p("Saffola Gold Pro Healthy Blended Oil (5 L)", "Saffola", 859, 940, 5, "l", 13, ["oil","saffola","gold","blended","tel","5l"], "instamart"),
    p("Gemini Pure Refined Sunflower Oil (1 L)", "Gemini", 143, 160, 1, "l", 13, ["oil","gemini","sunflower","tel","1l"], "instamart"),
    p("India Gate Basmati Rice Feast Rozzana (1 kg)", "India Gate", 99, 125, 1, "kg", 13, ["rice","india gate","basmati","chawal","rozzana","1kg"], "instamart"),
    p("India Gate Basmati Rice Feast Rozzana (5 kg)", "India Gate", 480, 580, 5, "kg", 13, ["rice","india gate","basmati","chawal","rozzana","5kg"], "instamart"),
    p("Daawat Super Basmati Rice (1 kg)", "Daawat", 136, 165, 1, "kg", 13, ["rice","daawat","basmati","chawal","1kg"], "instamart"),
    p("Daawat Super Basmati Rice (5 kg)", "Daawat", 626, 750, 5, "kg", 13, ["rice","daawat","basmati","chawal","5kg"], "instamart"),
    p("Tata Sampann Unpolished Toor Dal (1 kg)", "Tata Sampann", 180, 210, 1, "kg", 13, ["toor dal","dal","tata sampann","tur","arhar","1kg"], "instamart"),
    p("Tata Sampann Unpolished Toor Dal (500 g)", "Tata Sampann", 95, 110, 500, "g", 13, ["toor dal","dal","tata sampann","tur","arhar","500g"], "instamart"),
    p("Fortune Arhar Toor Dal (1 kg)", "Fortune", 170, 195, 1, "kg", 13, ["toor dal","dal","fortune","tur","arhar","1kg"], "instamart"),
    p("Brooke Bond Red Label Tea (250 g)", "Red Label", 123, 140, 250, "g", 13, ["tea","chai","red label","patti","250g"], "instamart"),
    p("Brooke Bond Red Label Tea (500 g)", "Red Label", 237, 270, 500, "g", 13, ["tea","chai","red label","patti","500g"], "instamart"),
    p("Tata Tea Gold (250 g)", "Tata Tea Gold", 139, 155, 250, "g", 13, ["tea","chai","tata tea","gold","250g"], "instamart"),
    p("Tata Tea Gold (500 g)", "Tata Tea Gold", 268, 295, 500, "g", 13, ["tea","chai","tata tea","gold","500g"], "instamart"),
    p("Wagh Bakri Premium Leaf Tea (500 g)", "Wagh Bakri", 253, 285, 500, "g", 13, ["tea","chai","wagh bakri","500g"], "instamart"),
    p("Nescafe Classic Instant Coffee Jar (50 g)", "Nescafe", 170, 185, 50, "g", 13, ["coffee","nescafe","classic","50g"], "instamart"),
    p("Nescafe Classic Instant Coffee Jar (100 g)", "Nescafe", 328, 360, 100, "g", 13, ["coffee","nescafe","classic","100g"], "instamart"),
    p("Bru Instant Coffee Jar (50 g)", "Bru", 126, 140, 50, "g", 13, ["coffee","bru","instant","50g"], "instamart"),
    p("Bru Instant Coffee Jar (100 g)", "Bru", 247, 275, 100, "g", 13, ["coffee","bru","instant","100g"], "instamart"),
    p("Eggoz Farm Fresh White Eggs (Pack of 6)", "Eggoz", 57, 65, 6, "pc", 13, ["eggs","egg","eggoz","anda","6","6pcs"], "instamart"),
    p("Eggoz Farm Fresh White Eggs (Pack of 10)", "Eggoz", 90, 100, 10, "pc", 13, ["eggs","egg","eggoz","anda","10","10pcs"], "instamart"),
    p("Eggoz Farm Fresh White Eggs (Pack of 12)", "Eggoz", 109, 120, 12, "pc", 13, ["eggs","egg","eggoz","anda","12","12pcs"], "instamart"),
    p("Farm Fresh Classic White Eggs (Pack of 6)", "Farm Fresh", 48, 55, 6, "pc", 13, ["eggs","egg","farm fresh","anda","6","6pcs"], "instamart"),
    p("Farm Fresh White Eggs Crate (Pack of 30)", "Farm Fresh", 217, 250, 30, "pc", 13, ["eggs","egg","farm fresh","anda","30","crate"], "instamart"),
    p("Britannia 100% Whole Wheat Bread (400 g)", "Britannia", 53, 55, 400, "g", 13, ["bread","britannia","wheat","brown bread","400g"], "instamart"),
    p("Britannia White Sandwich Bread (400 g)", "Britannia", 45, 50, 400, "g", 13, ["bread","britannia","white","sandwich","400g"], "instamart"),
    p("English Oven 100% Whole Wheat Brown Bread (400 g)", "English Oven", 48, 55, 400, "g", 13, ["bread","english oven","brown bread","wheat","400g"], "instamart"),
    p("Madhur Pure & Hygienic Sugar (1 kg)", "Madhur", 53, 60, 1, "kg", 13, ["sugar","madhur","chini","shakkar","1kg"], "instamart"),
    p("Madhur Pure & Hygienic Sugar (5 kg)", "Madhur", 247, 280, 5, "kg", 13, ["sugar","madhur","chini","shakkar","5kg"], "instamart"),
    p("Tata Salt Vacuum Evaporated (1 kg)", "Tata", 27, 28, 1, "kg", 13, ["salt","tata","namak","iodised","1kg"], "instamart"),
    p("Maggi 2-Minute Masala Instant Noodles (70 g)", "Nestle Maggi", 14, 14, 70, "g", 13, ["maggi","noodles","nestle","masala","single"], "instamart"),
    p("Maggi 2-Minute Masala Noodles Pack of 4 (280 g)", "Nestle Maggi", 55, 56, 280, "g", 13, ["maggi","noodles","nestle","masala","pack of 4","4"], "instamart"),
    p("Britannia Good Day Butter Cookies (600 g Value Pack)", "Britannia Good Day", 111, 130, 600, "g", 13, ["biscuit","biscuits","good day","britannia","butter cookies"], "instamart"),
    p("Parle-G Original Glucose Biscuits (800 g Family Pack)", "Parle-G", 76, 85, 800, "g", 13, ["biscuit","biscuits","parle-g","parle","glucose"], "instamart"),
    p("Sunfeast Dark Fantasy Choco Fills (300 g)", "Sunfeast", 136, 160, 300, "g", 13, ["biscuit","biscuits","dark fantasy","sunfeast","chocolate"], "instamart"),
    p("Fresh Onion (Pyaaz, 1 kg)", "Fresh Produce", 32, 40, 1, "kg", 13, ["onion","onions","pyaaz","kanda","1kg"], "instamart"),
    p("Fresh Potato (Aloo, 1 kg)", "Fresh Produce", 28, 35, 1, "kg", 13, ["potato","potatoes","aloo","alu","batata","1kg"], "instamart"),
    p("Fresh Hybrid Tomato (500 g)", "Fresh Produce", 20, 26, 500, "g", 13, ["tomato","tomatoes","tamatar","500g"], "instamart"),
    p("Fresh Robusta Banana (500 g / 4-5 pcs)", "Fresh Produce", 34, 42, 500, "g", 13, ["banana","bananas","kela","500g"], "instamart"),
    p("Fresh Lemon (Nimbu, Pack of 4)", "Fresh Produce", 22, 30, 4, "pc", 13, ["lemon","lemons","nimbu","4"], "instamart"),
    p("Fresh Coriander Leaves (Dhaniya, 100 g)", "Fresh Produce", 14, 20, 100, "g", 13, ["coriander","dhaniya","kothmir","100g"], "instamart"),
  ],
  flipkart: [
    p("Amul Taaza Toned Milk (500 ml)", "Amul", 27, 28, 500, "ml", 12, ["milk","amul","toned","doodh","taaza","500ml","500 ml"], "flipkart"),
    p("Amul Taaza Toned Milk (1 L)", "Amul", 55, 56, 1, "l", 12, ["milk","amul","toned","doodh","taaza","1l","1 l","1000ml"], "flipkart"),
    p("Amul Gold Full Cream Milk (500 ml)", "Amul", 34, 35, 500, "ml", 12, ["milk","amul","full cream","gold","doodh","500ml"], "flipkart"),
    p("Amul Gold Full Cream Milk (1 L)", "Amul", 66, 68, 1, "l", 12, ["milk","amul","full cream","gold","doodh","1l","1 l"], "flipkart"),
    p("Mother Dairy Toned Milk (500 ml)", "Mother Dairy", 27, 28, 500, "ml", 12, ["milk","mother dairy","toned","doodh","500ml"], "flipkart"),
    p("Mother Dairy Toned Milk (1 L)", "Mother Dairy", 55, 56, 1, "l", 12, ["milk","mother dairy","toned","doodh","1l"], "flipkart"),
    p("Mother Dairy Full Cream Milk (500 ml)", "Mother Dairy", 34, 35, 500, "ml", 12, ["milk","mother dairy","full cream","doodh","500ml"], "flipkart"),
    p("Mother Dairy Full Cream Milk (1 L)", "Mother Dairy", 66, 68, 1, "l", 12, ["milk","mother dairy","full cream","doodh","1l"], "flipkart"),
    p("Nandini Pasteurized Toned Milk (500 ml)", "Nandini", 24, 26, 500, "ml", 12, ["milk","nandini","toned","doodh","500ml"], "flipkart"),
    p("Nandini Pasteurized Toned Milk (1 L)", "Nandini", 47, 50, 1, "l", 12, ["milk","nandini","toned","doodh","1l"], "flipkart"),
    p("Aashirvaad Shudh Chakki Atta (1 kg)", "Aashirvaad", 60, 68, 1, "kg", 12, ["atta","aashirvaad","flour","wheat","1kg","chakki"], "flipkart"),
    p("Aashirvaad Shudh Chakki Atta (5 kg)", "Aashirvaad", 249, 275, 5, "kg", 12, ["atta","aashirvaad","flour","wheat","5kg","chakki"], "flipkart"),
    p("Aashirvaad Shudh Chakki Atta (10 kg)", "Aashirvaad", 473, 520, 10, "kg", 12, ["atta","aashirvaad","flour","wheat","10kg","chakki"], "flipkart"),
    p("Fortune Chakki Fresh Atta (5 kg)", "Fortune", 229, 260, 5, "kg", 12, ["atta","fortune","flour","wheat","5kg"], "flipkart"),
    p("Pillsbury Chakki Fresh Atta (5 kg)", "Pillsbury", 239, 270, 5, "kg", 12, ["atta","pillsbury","flour","wheat","5kg"], "flipkart"),
    p("Amul Salted Butter (100 g)", "Amul", 57, 60, 100, "g", 12, ["butter","amul","makhan","salted","100g"], "flipkart"),
    p("Amul Salted Butter (500 g)", "Amul", 273, 290, 500, "g", 12, ["butter","amul","makhan","salted","500g"], "flipkart"),
    p("Mother Dairy Table Butter (100 g)", "Mother Dairy", 56, 60, 100, "g", 12, ["butter","mother dairy","makhan","100g"], "flipkart"),
    p("Mother Dairy Table Butter (500 g)", "Mother Dairy", 268, 290, 500, "g", 12, ["butter","mother dairy","makhan","500g"], "flipkart"),
    p("Amul Malai Fresh Paneer (200 g)", "Amul", 90, 95, 200, "g", 12, ["paneer","amul","cottage cheese","malai","200g"], "flipkart"),
    p("Amul Malai Fresh Paneer (500 g)", "Amul", 219, 235, 500, "g", 12, ["paneer","amul","cottage cheese","malai","500g"], "flipkart"),
    p("Mother Dairy Classic Paneer (200 g)", "Mother Dairy", 88, 95, 200, "g", 12, ["paneer","mother dairy","cottage cheese","200g"], "flipkart"),
    p("Gowardhan Fresh Paneer Block (200 g)", "Gowardhan", 86, 95, 200, "g", 12, ["paneer","gowardhan","cottage cheese","200g"], "flipkart"),
    p("Amul Masti Dahi Curd (400 g)", "Amul", 33, 35, 400, "g", 12, ["curd","dahi","amul","masti","yogurt","400g"], "flipkart"),
    p("Amul Masti Dahi Tub (1 kg)", "Amul", 76, 85, 1, "kg", 12, ["curd","dahi","amul","masti","yogurt","1kg"], "flipkart"),
    p("Mother Dairy Ultimate Dahi (400 g)", "Mother Dairy", 33, 35, 400, "g", 12, ["curd","dahi","mother dairy","yogurt","400g"], "flipkart"),
    p("Milky Mist Set Curd (400 g)", "Milky Mist", 37, 40, 400, "g", 12, ["curd","dahi","milky mist","yogurt","400g"], "flipkart"),
    p("Fortune Sunlite Refined Sunflower Oil (1 L)", "Fortune", 141, 165, 1, "l", 12, ["oil","fortune","sunflower","tel","1l"], "flipkart"),
    p("Fortune Sunlite Refined Sunflower Oil (5 L)", "Fortune", 692, 785, 5, "l", 12, ["oil","fortune","sunflower","tel","5l"], "flipkart"),
    p("Saffola Gold Pro Healthy Blended Oil (1 L)", "Saffola", 171, 195, 1, "l", 12, ["oil","saffola","gold","blended","tel","1l"], "flipkart"),
    p("Saffola Gold Pro Healthy Blended Oil (5 L)", "Saffola", 829, 940, 5, "l", 12, ["oil","saffola","gold","blended","tel","5l"], "flipkart"),
    p("Gemini Pure Refined Sunflower Oil (1 L)", "Gemini", 138, 160, 1, "l", 12, ["oil","gemini","sunflower","tel","1l"], "flipkart"),
    p("India Gate Basmati Rice Feast Rozzana (1 kg)", "India Gate", 96, 125, 1, "kg", 12, ["rice","india gate","basmati","chawal","rozzana","1kg"], "flipkart"),
    p("India Gate Basmati Rice Feast Rozzana (5 kg)", "India Gate", 463, 580, 5, "kg", 12, ["rice","india gate","basmati","chawal","rozzana","5kg"], "flipkart"),
    p("Daawat Super Basmati Rice (1 kg)", "Daawat", 132, 165, 1, "kg", 12, ["rice","daawat","basmati","chawal","1kg"], "flipkart"),
    p("Daawat Super Basmati Rice (5 kg)", "Daawat", 605, 750, 5, "kg", 12, ["rice","daawat","basmati","chawal","5kg"], "flipkart"),
    p("Tata Sampann Unpolished Toor Dal (1 kg)", "Tata Sampann", 174, 210, 1, "kg", 12, ["toor dal","dal","tata sampann","tur","arhar","1kg"], "flipkart"),
    p("Tata Sampann Unpolished Toor Dal (500 g)", "Tata Sampann", 92, 110, 500, "g", 12, ["toor dal","dal","tata sampann","tur","arhar","500g"], "flipkart"),
    p("Fortune Arhar Toor Dal (1 kg)", "Fortune", 164, 195, 1, "kg", 12, ["toor dal","dal","fortune","tur","arhar","1kg"], "flipkart"),
    p("Brooke Bond Red Label Tea (250 g)", "Red Label", 119, 140, 250, "g", 12, ["tea","chai","red label","patti","250g"], "flipkart"),
    p("Brooke Bond Red Label Tea (500 g)", "Red Label", 229, 270, 500, "g", 12, ["tea","chai","red label","patti","500g"], "flipkart"),
    p("Tata Tea Gold (250 g)", "Tata Tea Gold", 135, 155, 250, "g", 12, ["tea","chai","tata tea","gold","250g"], "flipkart"),
    p("Tata Tea Gold (500 g)", "Tata Tea Gold", 258, 295, 500, "g", 12, ["tea","chai","tata tea","gold","500g"], "flipkart"),
    p("Wagh Bakri Premium Leaf Tea (500 g)", "Wagh Bakri", 244, 285, 500, "g", 12, ["tea","chai","wagh bakri","500g"], "flipkart"),
    p("Nescafe Classic Instant Coffee Jar (50 g)", "Nescafe", 164, 185, 50, "g", 12, ["coffee","nescafe","classic","50g"], "flipkart"),
    p("Nescafe Classic Instant Coffee Jar (100 g)", "Nescafe", 317, 360, 100, "g", 12, ["coffee","nescafe","classic","100g"], "flipkart"),
    p("Bru Instant Coffee Jar (50 g)", "Bru", 122, 140, 50, "g", 12, ["coffee","bru","instant","50g"], "flipkart"),
    p("Bru Instant Coffee Jar (100 g)", "Bru", 239, 275, 100, "g", 12, ["coffee","bru","instant","100g"], "flipkart"),
    p("Eggoz Farm Fresh White Eggs (Pack of 6)", "Eggoz", 55, 65, 6, "pc", 12, ["eggs","egg","eggoz","anda","6","6pcs"], "flipkart"),
    p("Eggoz Farm Fresh White Eggs (Pack of 10)", "Eggoz", 87, 100, 10, "pc", 12, ["eggs","egg","eggoz","anda","10","10pcs"], "flipkart"),
    p("Eggoz Farm Fresh White Eggs (Pack of 12)", "Eggoz", 105, 120, 12, "pc", 12, ["eggs","egg","eggoz","anda","12","12pcs"], "flipkart"),
    p("Farm Fresh Classic White Eggs (Pack of 6)", "Farm Fresh", 47, 55, 6, "pc", 12, ["eggs","egg","farm fresh","anda","6","6pcs"], "flipkart"),
    p("Farm Fresh White Eggs Crate (Pack of 30)", "Farm Fresh", 210, 250, 30, "pc", 12, ["eggs","egg","farm fresh","anda","30","crate"], "flipkart"),
    p("Britannia 100% Whole Wheat Bread (400 g)", "Britannia", 51, 55, 400, "g", 12, ["bread","britannia","wheat","brown bread","400g"], "flipkart"),
    p("Britannia White Sandwich Bread (400 g)", "Britannia", 44, 50, 400, "g", 12, ["bread","britannia","white","sandwich","400g"], "flipkart"),
    p("English Oven 100% Whole Wheat Brown Bread (400 g)", "English Oven", 47, 55, 400, "g", 12, ["bread","english oven","brown bread","wheat","400g"], "flipkart"),
    p("Madhur Pure & Hygienic Sugar (1 kg)", "Madhur", 51, 60, 1, "kg", 12, ["sugar","madhur","chini","shakkar","1kg"], "flipkart"),
    p("Madhur Pure & Hygienic Sugar (5 kg)", "Madhur", 239, 280, 5, "kg", 12, ["sugar","madhur","chini","shakkar","5kg"], "flipkart"),
    p("Tata Salt Vacuum Evaporated (1 kg)", "Tata", 26, 28, 1, "kg", 12, ["salt","tata","namak","iodised","1kg"], "flipkart"),
    p("Maggi 2-Minute Masala Instant Noodles (70 g)", "Nestle Maggi", 14, 14, 70, "g", 12, ["maggi","noodles","nestle","masala","single"], "flipkart"),
    p("Maggi 2-Minute Masala Noodles Pack of 4 (280 g)", "Nestle Maggi", 53, 56, 280, "g", 12, ["maggi","noodles","nestle","masala","pack of 4","4"], "flipkart"),
    p("Britannia Good Day Butter Cookies (600 g Value Pack)", "Britannia Good Day", 107, 130, 600, "g", 12, ["biscuit","biscuits","good day","britannia","butter cookies"], "flipkart"),
    p("Parle-G Original Glucose Biscuits (800 g Family Pack)", "Parle-G", 73, 85, 800, "g", 12, ["biscuit","biscuits","parle-g","parle","glucose"], "flipkart"),
    p("Sunfeast Dark Fantasy Choco Fills (300 g)", "Sunfeast", 132, 160, 300, "g", 12, ["biscuit","biscuits","dark fantasy","sunfeast","chocolate"], "flipkart"),
    p("Fresh Onion (Pyaaz, 1 kg)", "Fresh Produce", 31, 40, 1, "kg", 12, ["onion","onions","pyaaz","kanda","1kg"], "flipkart"),
    p("Fresh Potato (Aloo, 1 kg)", "Fresh Produce", 27, 35, 1, "kg", 12, ["potato","potatoes","aloo","alu","batata","1kg"], "flipkart"),
    p("Fresh Hybrid Tomato (500 g)", "Fresh Produce", 20, 26, 500, "g", 12, ["tomato","tomatoes","tamatar","500g"], "flipkart"),
    p("Fresh Robusta Banana (500 g / 4-5 pcs)", "Fresh Produce", 33, 42, 500, "g", 12, ["banana","bananas","kela","500g"], "flipkart"),
    p("Fresh Lemon (Nimbu, Pack of 4)", "Fresh Produce", 21, 30, 4, "pc", 12, ["lemon","lemons","nimbu","4"], "flipkart"),
    p("Fresh Coriander Leaves (Dhaniya, 100 g)", "Fresh Produce", 14, 20, 100, "g", 12, ["coriander","dhaniya","kothmir","100g"], "flipkart"),
  ],
  dmart: [
    p("Amul Taaza Toned Milk (500 ml)", "Amul", 25, 28, 500, "ml", 1440, ["milk","amul","toned","doodh","taaza","500ml","500 ml"], "dmart"),
    p("Amul Taaza Toned Milk (1 L)", "Amul", 51, 56, 1, "l", 1440, ["milk","amul","toned","doodh","taaza","1l","1 l","1000ml"], "dmart"),
    p("Amul Gold Full Cream Milk (500 ml)", "Amul", 32, 35, 500, "ml", 1440, ["milk","amul","full cream","gold","doodh","500ml"], "dmart"),
    p("Amul Gold Full Cream Milk (1 L)", "Amul", 62, 68, 1, "l", 1440, ["milk","amul","full cream","gold","doodh","1l","1 l"], "dmart"),
    p("Mother Dairy Toned Milk (500 ml)", "Mother Dairy", 25, 28, 500, "ml", 1440, ["milk","mother dairy","toned","doodh","500ml"], "dmart"),
    p("Mother Dairy Toned Milk (1 L)", "Mother Dairy", 51, 56, 1, "l", 1440, ["milk","mother dairy","toned","doodh","1l"], "dmart"),
    p("Mother Dairy Full Cream Milk (500 ml)", "Mother Dairy", 32, 35, 500, "ml", 1440, ["milk","mother dairy","full cream","doodh","500ml"], "dmart"),
    p("Mother Dairy Full Cream Milk (1 L)", "Mother Dairy", 62, 68, 1, "l", 1440, ["milk","mother dairy","full cream","doodh","1l"], "dmart"),
    p("Nandini Pasteurized Toned Milk (500 ml)", "Nandini", 23, 26, 500, "ml", 1440, ["milk","nandini","toned","doodh","500ml"], "dmart"),
    p("Nandini Pasteurized Toned Milk (1 L)", "Nandini", 44, 50, 1, "l", 1440, ["milk","nandini","toned","doodh","1l"], "dmart"),
    p("Aashirvaad Shudh Chakki Atta (1 kg)", "Aashirvaad", 56, 68, 1, "kg", 1440, ["atta","aashirvaad","flour","wheat","1kg","chakki"], "dmart"),
    p("Aashirvaad Shudh Chakki Atta (5 kg)", "Aashirvaad", 224, 275, 5, "kg", 1440, ["atta","aashirvaad","flour","wheat","5kg","chakki"], "dmart"),
    p("Aashirvaad Shudh Chakki Atta (10 kg)", "Aashirvaad", 427, 520, 10, "kg", 1440, ["atta","aashirvaad","flour","wheat","10kg","chakki"], "dmart"),
    p("Fortune Chakki Fresh Atta (5 kg)", "Fortune", 207, 260, 5, "kg", 1440, ["atta","fortune","flour","wheat","5kg"], "dmart"),
    p("Pillsbury Chakki Fresh Atta (5 kg)", "Pillsbury", 216, 270, 5, "kg", 1440, ["atta","pillsbury","flour","wheat","5kg"], "dmart"),
    p("Amul Salted Butter (100 g)", "Amul", 53, 60, 100, "g", 1440, ["butter","amul","makhan","salted","100g"], "dmart"),
    p("Amul Salted Butter (500 g)", "Amul", 255, 290, 500, "g", 1440, ["butter","amul","makhan","salted","500g"], "dmart"),
    p("Mother Dairy Table Butter (100 g)", "Mother Dairy", 52, 60, 100, "g", 1440, ["butter","mother dairy","makhan","100g"], "dmart"),
    p("Mother Dairy Table Butter (500 g)", "Mother Dairy", 250, 290, 500, "g", 1440, ["butter","mother dairy","makhan","500g"], "dmart"),
    p("Amul Malai Fresh Paneer (200 g)", "Amul", 84, 95, 200, "g", 1440, ["paneer","amul","cottage cheese","malai","200g"], "dmart"),
    p("Amul Malai Fresh Paneer (500 g)", "Amul", 205, 235, 500, "g", 1440, ["paneer","amul","cottage cheese","malai","500g"], "dmart"),
    p("Mother Dairy Classic Paneer (200 g)", "Mother Dairy", 82, 95, 200, "g", 1440, ["paneer","mother dairy","cottage cheese","200g"], "dmart"),
    p("Gowardhan Fresh Paneer Block (200 g)", "Gowardhan", 80, 95, 200, "g", 1440, ["paneer","gowardhan","cottage cheese","200g"], "dmart"),
    p("Amul Masti Dahi Curd (400 g)", "Amul", 31, 35, 400, "g", 1440, ["curd","dahi","amul","masti","yogurt","400g"], "dmart"),
    p("Amul Masti Dahi Tub (1 kg)", "Amul", 71, 85, 1, "kg", 1440, ["curd","dahi","amul","masti","yogurt","1kg"], "dmart"),
    p("Mother Dairy Ultimate Dahi (400 g)", "Mother Dairy", 31, 35, 400, "g", 1440, ["curd","dahi","mother dairy","yogurt","400g"], "dmart"),
    p("Milky Mist Set Curd (400 g)", "Milky Mist", 35, 40, 400, "g", 1440, ["curd","dahi","milky mist","yogurt","400g"], "dmart"),
    p("Fortune Sunlite Refined Sunflower Oil (1 L)", "Fortune", 132, 165, 1, "l", 1440, ["oil","fortune","sunflower","tel","1l"], "dmart"),
    p("Fortune Sunlite Refined Sunflower Oil (5 L)", "Fortune", 625, 785, 5, "l", 1440, ["oil","fortune","sunflower","tel","5l"], "dmart"),
    p("Saffola Gold Pro Healthy Blended Oil (1 L)", "Saffola", 159, 195, 1, "l", 1440, ["oil","saffola","gold","blended","tel","1l"], "dmart"),
    p("Saffola Gold Pro Healthy Blended Oil (5 L)", "Saffola", 748, 940, 5, "l", 1440, ["oil","saffola","gold","blended","tel","5l"], "dmart"),
    p("Gemini Pure Refined Sunflower Oil (1 L)", "Gemini", 129, 160, 1, "l", 1440, ["oil","gemini","sunflower","tel","1l"], "dmart"),
    p("India Gate Basmati Rice Feast Rozzana (1 kg)", "India Gate", 89, 125, 1, "kg", 1440, ["rice","india gate","basmati","chawal","rozzana","1kg"], "dmart"),
    p("India Gate Basmati Rice Feast Rozzana (5 kg)", "India Gate", 418, 580, 5, "kg", 1440, ["rice","india gate","basmati","chawal","rozzana","5kg"], "dmart"),
    p("Daawat Super Basmati Rice (1 kg)", "Daawat", 123, 165, 1, "kg", 1440, ["rice","daawat","basmati","chawal","1kg"], "dmart"),
    p("Daawat Super Basmati Rice (5 kg)", "Daawat", 546, 750, 5, "kg", 1440, ["rice","daawat","basmati","chawal","5kg"], "dmart"),
    p("Tata Sampann Unpolished Toor Dal (1 kg)", "Tata Sampann", 162, 210, 1, "kg", 1440, ["toor dal","dal","tata sampann","tur","arhar","1kg"], "dmart"),
    p("Tata Sampann Unpolished Toor Dal (500 g)", "Tata Sampann", 86, 110, 500, "g", 1440, ["toor dal","dal","tata sampann","tur","arhar","500g"], "dmart"),
    p("Fortune Arhar Toor Dal (1 kg)", "Fortune", 153, 195, 1, "kg", 1440, ["toor dal","dal","fortune","tur","arhar","1kg"], "dmart"),
    p("Brooke Bond Red Label Tea (250 g)", "Red Label", 111, 140, 250, "g", 1440, ["tea","chai","red label","patti","250g"], "dmart"),
    p("Brooke Bond Red Label Tea (500 g)", "Red Label", 214, 270, 500, "g", 1440, ["tea","chai","red label","patti","500g"], "dmart"),
    p("Tata Tea Gold (250 g)", "Tata Tea Gold", 126, 155, 250, "g", 1440, ["tea","chai","tata tea","gold","250g"], "dmart"),
    p("Tata Tea Gold (500 g)", "Tata Tea Gold", 241, 295, 500, "g", 1440, ["tea","chai","tata tea","gold","500g"], "dmart"),
    p("Wagh Bakri Premium Leaf Tea (500 g)", "Wagh Bakri", 228, 285, 500, "g", 1440, ["tea","chai","wagh bakri","500g"], "dmart"),
    p("Nescafe Classic Instant Coffee Jar (50 g)", "Nescafe", 153, 185, 50, "g", 1440, ["coffee","nescafe","classic","50g"], "dmart"),
    p("Nescafe Classic Instant Coffee Jar (100 g)", "Nescafe", 296, 360, 100, "g", 1440, ["coffee","nescafe","classic","100g"], "dmart"),
    p("Bru Instant Coffee Jar (50 g)", "Bru", 114, 140, 50, "g", 1440, ["coffee","bru","instant","50g"], "dmart"),
    p("Bru Instant Coffee Jar (100 g)", "Bru", 223, 275, 100, "g", 1440, ["coffee","bru","instant","100g"], "dmart"),
    p("Eggoz Farm Fresh White Eggs (Pack of 6)", "Eggoz", 51, 65, 6, "pc", 1440, ["eggs","egg","eggoz","anda","6","6pcs"], "dmart"),
    p("Eggoz Farm Fresh White Eggs (Pack of 10)", "Eggoz", 81, 100, 10, "pc", 1440, ["eggs","egg","eggoz","anda","10","10pcs"], "dmart"),
    p("Eggoz Farm Fresh White Eggs (Pack of 12)", "Eggoz", 98, 120, 12, "pc", 1440, ["eggs","egg","eggoz","anda","12","12pcs"], "dmart"),
    p("Farm Fresh Classic White Eggs (Pack of 6)", "Farm Fresh", 44, 55, 6, "pc", 1440, ["eggs","egg","farm fresh","anda","6","6pcs"], "dmart"),
    p("Farm Fresh White Eggs Crate (Pack of 30)", "Farm Fresh", 196, 250, 30, "pc", 1440, ["eggs","egg","farm fresh","anda","30","crate"], "dmart"),
    p("Britannia 100% Whole Wheat Bread (400 g)", "Britannia", 47, 55, 400, "g", 1440, ["bread","britannia","wheat","brown bread","400g"], "dmart"),
    p("Britannia White Sandwich Bread (400 g)", "Britannia", 41, 50, 400, "g", 1440, ["bread","britannia","white","sandwich","400g"], "dmart"),
    p("English Oven 100% Whole Wheat Brown Bread (400 g)", "English Oven", 44, 55, 400, "g", 1440, ["bread","english oven","brown bread","wheat","400g"], "dmart"),
    p("Madhur Pure & Hygienic Sugar (1 kg)", "Madhur", 47, 60, 1, "kg", 1440, ["sugar","madhur","chini","shakkar","1kg"], "dmart"),
    p("Madhur Pure & Hygienic Sugar (5 kg)", "Madhur", 216, 280, 5, "kg", 1440, ["sugar","madhur","chini","shakkar","5kg"], "dmart"),
    p("Tata Salt Vacuum Evaporated (1 kg)", "Tata", 25, 28, 1, "kg", 1440, ["salt","tata","namak","iodised","1kg"], "dmart"),
    p("Maggi 2-Minute Masala Instant Noodles (70 g)", "Nestle Maggi", 13, 14, 70, "g", 1440, ["maggi","noodles","nestle","masala","single"], "dmart"),
    p("Maggi 2-Minute Masala Noodles Pack of 4 (280 g)", "Nestle Maggi", 49, 56, 280, "g", 1440, ["maggi","noodles","nestle","masala","pack of 4","4"], "dmart"),
    p("Britannia Good Day Butter Cookies (600 g Value Pack)", "Britannia Good Day", 100, 130, 600, "g", 1440, ["biscuit","biscuits","good day","britannia","butter cookies"], "dmart"),
    p("Parle-G Original Glucose Biscuits (800 g Family Pack)", "Parle-G", 68, 85, 800, "g", 1440, ["biscuit","biscuits","parle-g","parle","glucose"], "dmart"),
    p("Sunfeast Dark Fantasy Choco Fills (300 g)", "Sunfeast", 123, 160, 300, "g", 1440, ["biscuit","biscuits","dark fantasy","sunfeast","chocolate"], "dmart"),
    p("Fresh Onion (Pyaaz, 1 kg)", "Fresh Produce", 29, 40, 1, "kg", 1440, ["onion","onions","pyaaz","kanda","1kg"], "dmart"),
    p("Fresh Potato (Aloo, 1 kg)", "Fresh Produce", 25, 35, 1, "kg", 1440, ["potato","potatoes","aloo","alu","batata","1kg"], "dmart"),
    p("Fresh Hybrid Tomato (500 g)", "Fresh Produce", 18, 26, 500, "g", 1440, ["tomato","tomatoes","tamatar","500g"], "dmart"),
    p("Fresh Robusta Banana (500 g / 4-5 pcs)", "Fresh Produce", 31, 42, 500, "g", 1440, ["banana","bananas","kela","500g"], "dmart"),
    p("Fresh Lemon (Nimbu, Pack of 4)", "Fresh Produce", 20, 30, 4, "pc", 1440, ["lemon","lemons","nimbu","4"], "dmart"),
    p("Fresh Coriander Leaves (Dhaniya, 100 g)", "Fresh Produce", 13, 20, 100, "g", 1440, ["coriander","dhaniya","kothmir","100g"], "dmart"),
  ],
}

export const SUGGESTED_ITEMS = [
  "Milk",
  "Atta",
  "Butter",
  "Eggs",
  "Bread",
  "Curd",
  "Paneer",
  "Cooking Oil",
  "Basmati Rice",
  "Toor Dal",
  "Tea",
  "Coffee",
  "Sugar",
  "Salt",
  "Maggi",
  "Biscuits",
  "Onion",
  "Potato",
  "Tomato",
  "Banana",
]
